---

# Boxed installation playbook
# ---------------------------

# A Simple, straight playbook for producing
# a boxed installation in a vagrant VM.


- name: 'Boxed installation'

  hosts: vagrant

  # vars:
    # custom_configuration: value

  roles:
    - '.'    # The current directory itself is the role

